version: "3.9"

services:
  app:
    build:
      dockerfile: ./app/Dockerfile
    volumes:
      - ../src/:/app
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ../src/:/app
